project_id = "yztogmdixmchsmimtent"

[functions.promotions]
verify_jwt = false

[functions."auto-start-gigs"]
verify_jwt = false

[functions.progression]
verify_jwt = false

[functions.book-reading-attendance]
verify_jwt = false

[functions.shift-clock-out]
verify_jwt = false

[functions.generate-song-lyrics]
verify_jwt = false

[functions.twaater-outcome-engine]
verify_jwt = false

[functions.university-attendance]
verify_jwt = false

[functions.cleanup-songwriting]
verify_jwt = false

[functions.complete-rehearsals]
verify_jwt = false

[functions.calculate-weekly-activity]
verify_jwt = false

[functions.complete-recording-sessions]
verify_jwt = false

[functions.suggest-accounts]
verify_jwt = false

[functions.process-gig-song]
verify_jwt = false

[functions.complete-gig]
verify_jwt = false

[functions.auto-complete-gigs]
verify_jwt = false

[functions.process-scheduled-activities]
verify_jwt = false

[functions.generate-gig-offers]
verify_jwt = false

[functions.update-daily-streams]
verify_jwt = false

[functions.complete-release-manufacturing]
verify_jwt = false